sylius_shop_checkout_start:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: sylius_shop_checkout_address

sylius_shop_checkout_address:
    path: /address
    methods: [GET, PUT]
    defaults:
        _controller: sylius.controller.order:updateAction
        _sylius:
            event: address
            flash: false
            template: VcareWebBundle:Checkout:address.html.twig
            form:
                type: Sylius\Bundle\CoreBundle\Form\Type\Checkout\AddressType
                options:
                    customer: expr:service('sylius.context.customer').getCustomer()
            repository:
                method: find
                arguments:
                    - "expr:service('sylius.context.cart').getCart()"
            state_machine:
                graph: sylius_order_checkout
                transition: address
            redirect:
                route: sylius_shop_checkout_select_shipping
                parameters: []

sylius_shop_checkout_select_shipping:
    path: /select-shipping
    methods: [GET, PUT]
    defaults:
        _controller: sylius.controller.order:updateAction
        _sylius:
            event: select_shipping
            flash: false
            template: VcareWebBundle:Checkout:shipping.html.twig
            form: Sylius\Bundle\CoreBundle\Form\Type\Checkout\SelectShippingType
            repository:
                method: find
                arguments:
                    - "expr:service('sylius.context.cart').getCart()"
            state_machine:
                graph: sylius_order_checkout
                transition: select_shipping
            redirect:
                route: sylius_shop_checkout_select_payment
                parameters: []

sylius_shop_checkout_select_payment:
    path: /select-payment
    methods: [GET, PUT]
    defaults:
        _controller: sylius.controller.order:updateAction
        _sylius:
            event: payment
            flash: false
            template: VcareWebBundle:Checkout:payment.html.twig
            form: Sylius\Bundle\CoreBundle\Form\Type\Checkout\SelectPaymentType
            repository:
                method: find
                arguments:
                    - "expr:service('sylius.context.cart').getCart()"
            state_machine:
                graph: sylius_order_checkout
                transition: select_payment
            redirect:
                route: sylius_shop_checkout_complete
                parameters: []

sylius_shop_checkout_complete:
    path: /complete
    methods: [GET, PUT]
    defaults:
        _controller: sylius.controller.order:updateAction
        _sylius:
            event: complete
            flash: false
            template: VcareWebBundle:Checkout:complete.html.twig
            repository:
                method: find
                arguments:
                    - "expr:service('sylius.context.cart').getCart()"
            state_machine:
                graph: sylius_order_checkout
                transition: complete
            redirect:
                route: sylius_shop_order_pay
                parameters:
                    tokenValue: resource.tokenValue
            form:
                type: Sylius\Bundle\CoreBundle\Form\Type\Checkout\CompleteType
                options:
                    validation_groups: 'sylius_checkout_complete'

sylius_shop_checkout_change_address_book:
    path: /change-address-book/{addressId}/{addressType}
    methods: [GET]
    defaults:
        _controller: sylius.controller.order:changeAddressingAction
        _sylius:
            flash: false
            repository:
                method: find
                arguments: [expr:service('sylius.context.cart').getCart()]
            redirect:
                route: sylius_shop_checkout_address
            state_machine:
                graph: sylius_order_checkout
                transition: address

sylius_shop_checkout_address_books:
    path: /address-books
    methods: [GET]
    defaults:
        _controller: sylius.controller.address:indexAction
        _sylius:
            template: VcareWebBundle:Checkout:_address_books.html.twig
            paginate: false
            repository:
                method: findByCustomer
                arguments:
                    - 'expr:service("sylius.context.customer").getCustomer()'
